general {
  unding = -1
    o(24uter_col
    nput = false    check_color = rgba(204, 136, 34, 0)
        fail_color = rgba(204, 34, 34, 0) # if authentication failed, changes outer_color and fail message outer_color    fail_text = $FAIL <b>($ATTEMPTS)</b> # can be set to empty    fail_transition = 300 # transition time in ms between normal outer_color and fail_color    capslock_color = -1
            numlock_color = -outer_color    bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
                invert_numlock = false # change color if numlock is off    swap_font_color = false # see below
                    position = 0, -468    halign = center
                        valign = center}

                        label {
                            monitor = 
                              text = cmd[update:1000] echo "$(~/.config/Scripts/song-status)"
                                color = rgba(242, 243, 244, 0.75)
                                  font_size = 14
                                    font_family = SF Pro text  position = 20, 512
                                      halign = left  valign = center}
:q

                                      label {
                                          monitor =
                                            text = cmd[update:1000] echo "$(~/.config/Scripts/network-status)‎"
                                              color = rgba(242, 243, 244, 0.75)
                                                font_size = 16
                                                  font_family = SF Pro text  position = locknde = pidof hyprlock || hyprlock || hyprlock -c ~/.local/src/Brain_Shell/src/config/hyprlock.conf       # avoid starting multiple hyprlock instances.
    r = rgba
    beforede_on_e_sleep_cmd = loginctl lock-session    # lock before suspend.
    #afterlse
    #    place_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
    #    lder_
}

listener {
    timeout = 300                                # 5min.
    on-timeout = brightnessctl -s set 0         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}

listener {
    timeout = 330                                 # 5.5min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 360                                                    # 6min
    on-timeout = brightnessctl -s set 0               # screen off when timeout has passed
    on-resume = brightnessctl -r          # screen on when activity is detected after timeout has fired.
}
nner_co
r = rgba
r(2g
listener {
    timeout = 900                                # 15min
    on-timeout = systemctl suspend                # suspend pc
}
